# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    setup_ci if ENV['CI']
    run_tests(scheme: "octospoon")
  end

  desc "Deploy to App Store"
  lane :release do
    setup_ci if ENV['CI']
    match(
      type: "appstore",
      git_basic_authorization: Base64.strict_encode64(ENV['GIT_PERSONAL_ACCESS_TOKEN'])
    )

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY']
    )

    increment_build_number({
     build_number: latest_testflight_build_number + 1
  })
    build_app(
		scheme: ENV['GYM_SCHEME'],
		export_method: "app-store",
		silent: true
	)
	upload_to_testflight(
		skip_waiting_for_build_processing: true,
		apple_id: ENV['APPLE_ID']
	)
  end

  desc "Will get provisioning profiles for development and releases " + 
"for the current environment."
  lane :certify do
    types = ["development", "appstore"]
    for type in types
      match(
        type: type, 
        app_identifier: ENV['MATCH_APP_IDENTIFIER']
      )
    end
  end
end