name: test-ios-app
on:
  push:
    branches:
      - 'staging'
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: latest
      - uses: actions/checkout@v2
      - run: fastlane release